/**
 * Demo fixtures for the statement screen. Every amount is in **integer cents**.
 *
 * TODO(open-finance, bet-detection): replace with
 * `container.listTransactions.execute({ userId, period })`. Nothing here may
 * become business logic — it is display data and nothing else.
 *
 * Kept deliberately consistent with `../dashboard/_mock-snapshot.ts`: the eleven
 * betting entries inside the last 30 days sum to R$ 1.840,00, which is the
 * monthly figure the dashboard hero shows. Change one and change the other.
 *
 * Entries are authored as offsets from a reference day rather than as absolute
 * dates so that "Hoje" and "Ontem" stay true whenever the demo is opened.
 */
import type { LedgerEntry, PaymentMethod } from './_ledger-entry';

type LedgerEntryDraft = Omit<LedgerEntry, 'id' | 'occurredAt'> & {
  readonly daysAgo: number;
  /** Local time of day, `HH:MM`. */
  readonly at: string;
};

const MILLISECONDS_PER_DAY = 86_400_000;

const DRAFTS: readonly LedgerEntryDraft[] = [
  {
    daysAgo: 0,
    at: '21:47',
    counterparty: 'Bet365',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -50_000,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 0,
    at: '19:12',
    counterparty: 'Supermercado Pão de Açúcar',
    category: 'Mercado',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -18_740,
    status: 'SETTLED',
  },
  {
    daysAgo: 0,
    at: '12:38',
    counterparty: 'iFood',
    category: 'Alimentação',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -3_290,
    status: 'PENDING',
  },
  {
    daysAgo: 1,
    at: '22:03',
    counterparty: 'Betano',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -15_000,
    status: 'SETTLED',
    bet: { matchedBy: 'LICENSED_CNPJ', confidence: 'HIGH' },
  },
  {
    daysAgo: 1,
    at: '12:30',
    counterparty: 'iFood',
    category: 'Alimentação',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -5_490,
    status: 'SETTLED',
  },
  {
    daysAgo: 2,
    at: '23:18',
    counterparty: 'Betano',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -10_000,
    status: 'SETTLED',
    bet: { matchedBy: 'LICENSED_CNPJ', confidence: 'HIGH' },
  },
  {
    daysAgo: 2,
    at: '08:55',
    counterparty: 'Uber',
    category: 'Transporte',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -2_370,
    status: 'SETTLED',
  },
  {
    daysAgo: 3,
    at: '20:41',
    counterparty: 'Bet365',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -25_000,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 3,
    at: '10:07',
    counterparty: 'Drogasil',
    category: 'Saúde',
    accountId: 'andorinha-checking',
    method: 'DEBIT_CARD',
    amountInCents: -4_180,
    status: 'SETTLED',
  },
  {
    daysAgo: 4,
    at: '23:52',
    counterparty: 'Esportes da Sorte',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -7_500,
    status: 'SETTLED',
    bet: { matchedBy: 'DESCRIPTION_KEYWORD', confidence: 'LOW' },
  },
  {
    daysAgo: 4,
    at: '17:20',
    counterparty: 'Posto Ipiranga',
    category: 'Transporte',
    accountId: 'andorinha-checking',
    method: 'DEBIT_CARD',
    amountInCents: -12_000,
    status: 'SETTLED',
  },
  {
    daysAgo: 5,
    at: '21:09',
    counterparty: 'Blaze',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -12_000,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 5,
    at: '06:00',
    counterparty: 'Netflix',
    category: 'Assinaturas',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -5_590,
    status: 'SETTLED',
  },
  {
    daysAgo: 6,
    at: '22:34',
    counterparty: 'Betano',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -8_000,
    status: 'SETTLED',
    bet: { matchedBy: 'LICENSED_CNPJ', confidence: 'HIGH' },
  },
  {
    daysAgo: 6,
    at: '07:42',
    counterparty: 'Padaria Real',
    category: 'Alimentação',
    accountId: 'andorinha-checking',
    method: 'DEBIT_CARD',
    amountInCents: -1_850,
    status: 'SETTLED',
  },
  {
    daysAgo: 7,
    at: '09:00',
    counterparty: 'Salário',
    category: 'Renda',
    accountId: 'andorinha-checking',
    method: 'TRANSFER',
    amountInCents: 320_000,
    status: 'SETTLED',
  },
  {
    daysAgo: 7,
    at: '09:05',
    counterparty: 'Aluguel',
    category: 'Moradia',
    accountId: 'andorinha-checking',
    method: 'DIRECT_DEBIT',
    amountInCents: -140_000,
    status: 'SETTLED',
  },
  {
    daysAgo: 8,
    at: '23:41',
    counterparty: 'Blaze',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -20_000,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 8,
    at: '18:22',
    counterparty: 'Uber',
    category: 'Transporte',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -2_370,
    status: 'SETTLED',
  },
  {
    daysAgo: 9,
    at: '20:15',
    counterparty: 'Bet365',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -15_000,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 9,
    at: '11:48',
    counterparty: 'Supermercado Extra',
    category: 'Mercado',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -9_630,
    status: 'SETTLED',
  },
  {
    daysAgo: 10,
    at: '06:00',
    counterparty: 'Spotify',
    category: 'Assinaturas',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -2_190,
    status: 'SETTLED',
  },
  {
    daysAgo: 11,
    at: '21:57',
    counterparty: 'Sportingbet',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -9_500,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 11,
    at: '15:03',
    counterparty: 'Amazon',
    category: 'Compras',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -7_899,
    status: 'SETTLED',
  },
  {
    daysAgo: 12,
    at: '19:26',
    counterparty: 'Uber',
    category: 'Transporte',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -1_990,
    status: 'SETTLED',
  },
  {
    daysAgo: 13,
    at: '22:11',
    counterparty: 'Betano',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -12_000,
    status: 'SETTLED',
    bet: { matchedBy: 'LICENSED_CNPJ', confidence: 'HIGH' },
  },
  {
    daysAgo: 13,
    at: '08:30',
    counterparty: 'Academia SmartFit',
    category: 'Saúde',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -9_990,
    status: 'SETTLED',
  },
  {
    daysAgo: 14,
    at: '16:44',
    counterparty: 'Pix recebido · João M.',
    category: 'Transferências',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: 8_000,
    status: 'SETTLED',
  },
  {
    daysAgo: 20,
    at: '11:12',
    counterparty: 'Supermercado Pão de Açúcar',
    category: 'Mercado',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -21_050,
    status: 'SETTLED',
  },
  {
    daysAgo: 25,
    at: '09:30',
    counterparty: 'Conta de luz',
    category: 'Moradia',
    accountId: 'andorinha-checking',
    method: 'BOLETO',
    amountInCents: -18_730,
    status: 'SETTLED',
  },
  {
    daysAgo: 28,
    at: '20:05',
    counterparty: 'iFood',
    category: 'Alimentação',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -4_720,
    status: 'SETTLED',
  },
  {
    daysAgo: 33,
    at: '13:19',
    counterparty: 'Uber',
    category: 'Transporte',
    accountId: 'vela-credit',
    method: 'CREDIT_CARD',
    amountInCents: -3_110,
    status: 'SETTLED',
  },
  {
    daysAgo: 34,
    at: '22:48',
    counterparty: 'Blaze',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -30_000,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 37,
    at: '09:00',
    counterparty: 'Salário',
    category: 'Renda',
    accountId: 'andorinha-checking',
    method: 'TRANSFER',
    amountInCents: 320_000,
    status: 'SETTLED',
  },
  {
    daysAgo: 37,
    at: '09:05',
    counterparty: 'Aluguel',
    category: 'Moradia',
    accountId: 'andorinha-checking',
    method: 'DIRECT_DEBIT',
    amountInCents: -140_000,
    status: 'SETTLED',
  },
  {
    daysAgo: 41,
    at: '21:33',
    counterparty: 'Bet365',
    category: 'Apostas',
    accountId: 'andorinha-checking',
    method: 'PIX',
    amountInCents: -18_000,
    status: 'SETTLED',
    bet: { matchedBy: 'GAMBLING_MCC', confidence: 'HIGH' },
  },
  {
    daysAgo: 44,
    at: '10:26',
    counterparty: 'Drogasil',
    category: 'Saúde',
    accountId: 'andorinha-checking',
    method: 'DEBIT_CARD',
    amountInCents: -2_690,
    status: 'SETTLED',
  },
];

export const METHOD_LABELS: Readonly<Record<PaymentMethod, string>> = {
  PIX: 'Pix',
  CREDIT_CARD: 'Cartão de crédito',
  DEBIT_CARD: 'Cartão de débito',
  DIRECT_DEBIT: 'Débito automático',
  TRANSFER: 'Transferência',
  BOLETO: 'Boleto',
};

function toOccurredAt(reference: Date, draft: LedgerEntryDraft): string {
  const day = new Date(reference.getTime() - draft.daysAgo * MILLISECONDS_PER_DAY);
  const [hours, minutes] = draft.at.split(':');
  day.setHours(Number(hours), Number(minutes), 0, 0);
  return day.toISOString();
}

/** Newest first — the order every statement screen shows. */
export function buildLedgerEntries(reference: Date): readonly LedgerEntry[] {
  return DRAFTS.map((draft, index) => ({
    id: `entry-${index + 1}`,
    occurredAt: toOccurredAt(reference, draft),
    counterparty: draft.counterparty,
    category: draft.category,
    accountId: draft.accountId,
    method: draft.method,
    amountInCents: draft.amountInCents,
    status: draft.status,
    ...(draft.bet ? { bet: draft.bet } : {}),
  }));
}
